### ISSUE TITLE
Fail to work on common picture

### ISSUE THREAD

**Issue by Mrw33554432** [pkhungurn/talking-head-anime-3-demo#13]
I tried several times with images that were not from the data folder, and they were turned into a mess every single time. I also tried some vtuber images from google that are quite simple, but none of them works correctly. Feel like an underfitting/overfitting issue. And yes, they work perfectly for those images from the data folder.

**Comment by Mrw33554432** [comment]
I even manually added hands and legs to some of them but still failed to make it.
![de2cfe5-a554e7d6-f204-434a-ae3a-236e58c73bf2](https://user-images.githubusercontent.com/102270023/221068574-eeb51413-5893-4040-a042-48134a845491.png)
![u2](https://user-images.githubusercontent.com/102270023/221069090-93645eab-54a9-4e65-81c6-5ee94ba6374c.png)
![My project (2)](https://user-images.githubusercontent.com/102270023/221068619-817a1a9d-c321-4967-8a58-f0e1df84bf30.png)

**Comment by Mrw33554432** [comment]
some of the pictures I uploaded here is not the modified version, but the modified versions also fail to work

**Comment by Fruitpex** [comment]
I tried the third image and it worked fine for me.
Did you set it as 512x512 and make the background transparent?

**Comment by Mrw33554432** [comment]
> I tried the third image and it worked fine for me. Did you set it as 512x512 and make the background transparent?
I think I did, but I will retry it later!

**Comment by dragonmeteor** [comment]
Please refer to the constraints on the images here.
The most important constraint is that it must have an alpha channel, and, as Fruitpex said, the background must be transparent.
The first image will not work well because the character is not front facing.
https://github.com/pkhungurn/talking-head-anime-3-demo#contraints-on-input-images

**Comment by Mrw33554432** [comment]
> Please refer to the constraints on the images here.
> The most important constraint is that it must have an alpha channel, and, as Fruitpex said, the background must be transparent.
> The first image will not work well because the character is not front facing.
> https://github.com/pkhungurn/talking-head-anime-3-demo#contraints-on-input-images

You are right, I made a stupid mistake that I was too concentrated on the ratio between body parts but forgot to remove the white background. Sorry!
