### ISSUE TITLE
Uploading models to Huggingface

### ISSUE THREAD

**Issue by alpkabac** [pkhungurn/talking-head-anime-3-demo#15]
I wanted to ask If I am allowed to upload the models to HF with full credit to you. I am asking this because platforms like Dropbox are unreliable and many other projects have been lost due to hosting issues.

**Comment by pkhungurn** [comment]
Yes. The code is released under the MIT license, and the models are released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/legalcode) license. You are free to do anything as long as you comply with the license.
