### ISSUE TITLE
Website 【Talking Head(?) Anime from a Single Image 3】 Page not found

### ISSUE THREAD

**Issue by Cobra30621** [pkhungurn/talking-head-anime-3-demo#3]
When I open [Talking Head(?) Anime from a Single Image 3: Now the Body Too](https://pkhungurn.github.io/talking-head-anime-3/index.html), shows a page not found.
![image](https://user-images.githubusercontent.com/44718953/185327838-6979d09e-b913-4fbe-a274-26cd26746063.png)

**Comment by dragonmeteor** [comment]
I have to take down the web pages because of copyright issues: https://twitter.com/dragonmeteor/status/1550712533342101504. I'm not actively working to bring them back at the moment due to lack of motivation and time.

**Comment by Cobra30621** [comment]
I understand.
I hope someday the article can come back, I like your job and want to study the technology behind it.

**Comment by abhay-sheshadri** [comment]
An archived version of the webpage appears to be at https://web.archive.org/web/20220606073558/https://pkhungurn.github.io/talking-head-anime-3/index.html

**Comment by Cobra30621** [comment]
Got it.
Thank you so much.
